CREATE TABLE TRAINER_T
(
    T_ID          INT             NOT NULL, 
    T_NAME        VARCHAR2(20)    NOT NULL, 
    T_RRN         VARCHAR2(20)    NOT NULL, 
    T_TEL         VARCHAR2(30)    NOT NULL, 
    T_ADDRESS     VARCHAR2(40)    NOT NULL, 
    T_JOB_TYPE    VARCHAR2(20)    NOT NULL, 
    T_RANK        VARCHAR2(20)    NOT NULL, 
    T_SALARY      VARCHAR2(20)    NOT NULL, 
    CONSTRAINT PK_TRAINER_T PRIMARY KEY (T_ID)
)
/

CREATE SEQUENCE TRAINER_T_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TRAINER_T_AI_TRG
BEFORE INSERT ON TRAINER_T 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TRAINER_T_SEQ.NEXTVAL
    INTO :NEW.T_ID
    FROM DUAL;
END;
/

--DROP TRIGGER TRAINER_T_AI_TRG;
/

--DROP SEQUENCE TRAINER_T_SEQ;
/

COMMENT ON TABLE TRAINER_T IS '트레이너테이블'
/

COMMENT ON COLUMN TRAINER_T.T_ID IS '트레이너ID'
/

COMMENT ON COLUMN TRAINER_T.T_NAME IS '트레이너 이름'
/

COMMENT ON COLUMN TRAINER_T.T_RRN IS '트레이너 주민등록번호'
/

COMMENT ON COLUMN TRAINER_T.T_TEL IS '트레이너 연락처'
/

COMMENT ON COLUMN TRAINER_T.T_ADDRESS IS '트레이너 주소'
/

COMMENT ON COLUMN TRAINER_T.T_JOB_TYPE IS '고용형태'
/

COMMENT ON COLUMN TRAINER_T.T_RANK IS '트레이너 직급'
/

COMMENT ON COLUMN TRAINER_T.T_SALARY IS '트레이너 급여'
/

INSERT INTO TRAINER_T VALUES(1, '박스쾃', '971214-124111', '010-0115-7415', '대구광역시 북구 동부로 1341', '정규직', '팀장', '3000')