CREATE TABLE ADMIN_T
(
    ADMIN_ID      VARCHAR2(20)    NOT NULL, 
    ADMIN_PW      VARCHAR2(20)    NOT NULL, 
    ADMIN_NAME    VARCHAR2(20)    NOT NULL, 
    ADMIN_RRN     VARCHAR2(20)    NOT NULL, 
    ADMIN_TEL     VARCHAR2(20)    NOT NULL, 
    CONSTRAINT PK_ADMIN_T PRIMARY KEY (ADMIN_ID)
)
/

COMMENT ON TABLE ADMIN_T IS 'ADMIN_T'
/

COMMENT ON COLUMN ADMIN_T.ADMIN_ID IS '包府磊 ID'
/

COMMENT ON COLUMN ADMIN_T.ADMIN_PW IS '包府磊 PW'
/

COMMENT ON COLUMN ADMIN_T.ADMIN_NAME IS '包府磊 捞抚'
/

COMMENT ON COLUMN ADMIN_T.ADMIN_RRN IS '包府磊 林刮殿废锅龋'
/

COMMENT ON COLUMN ADMIN_T.ADMIN_TEL IS '包府磊 楷遏贸'
/
INSERT INTO ADMIN_T VALUES('ADMIN', '1234', '辫包府', '911111-1111111', '010-1111-1111')
SELECT ADMIN_ID as ID, ADMIN_PW as PW FROM ADMIN_T WHERE ADMIN_ID = 'ADMIN' AND ADMIN_PW = '1234'
commit;